Feature/contact
web-architectures-project/SkillVista-backend pull request #44
Opened 2023-10-20 23:11 UTC by call203

- Provider
 I made Provider successfully and mostly similar as User.
But I'm not sure if I managed the Jest file. I'd appreciate it if @1Solon could take a look at that.

- Contact
Guys. I think we need to discuss a problem that I found in Contact table.
 As you see, **user_id and provider_id is unique keys** and foreign keys, which means can not go without unique.
I made all of CRUD API, but I didn't work to generate multiple rows with same user_id and provider_id.
![Screenshot 2023-10-21 at 00 04 58](https://github.com/web-architectures-project/SkillVista-backend/assets/57412714/287b04c6-788e-4742-9775-914d8252a2c9)

2023-10-21 11:36 UTC, 1Solon commented
@call203 unsure if you saw in the WhatsApp, but you should be able to get away with just removing "@unique" from both on the contacts schema. Prisma should protect the foreign key relationship itself. 

Let me know when that's pushed and I'll review

2023-10-21 11:39 UTC, 1Solon requested changes
@call203 unsure if you saw in the WhatsApp, but you should be able to get away with just removing "@unique" from both on the contacts schema. Prisma should protect the foreign key relationship itself. 

Also, some of the tests are failing. It seems to be unable to locate Bcrypt, let me know if you need help fixing that.

Let me know when that's pushed and I'll review

2023-10-21 12:14 UTC, call203 commented
> @call203 unsure if you saw in the WhatsApp, but you should be able to get away with just removing "@unique" from both on the contacts schema. Prisma should protect the foreign key relationship itself.
> 
> Also, some of the tests are failing. It seems to be unable to locate Bcrypt, let me know if you need help fixing that.
> 
> Let me know when that's pushed and I'll review

I fixed it @1Solon!

2023-10-23 12:28 UTC, 1Solon approved these changes

2023-10-23 12:28 UTC, merged